spring.application.name=Assessment

spring.datasource.url=jdbc:postgresql://localhost:5432/infnet_db
spring.datasource.username=admin
spring.datasource.password=123

#  Não usar update ou 'create' na entrega
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Faz o Hibernate imprimir o SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mostra os valores que entram nos "?" da query
logging.level.org.hibernate.orm.jdbc.bind=trace