spring.application.name=Assessment

spring.datasource.url=jdbc:postgresql://localhost:5432/infnet_db
spring.datasource.username=admin
spring.datasource.password=123

#  Não usa update ou 'create' na entrega
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true